import{fireEvent,render,screen,within}from"@testing-library/react";import Home from"@/app/page";import{LocaleProvider}from"@/i18n/locale-provider";
const renderHome=()=>render(<LocaleProvider><Home/></LocaleProvider>);
describe("finance home",()=>{
beforeEach(()=>localStorage.clear());
it("uses separate responsive layouts with English as the default",()=>{renderHome();const desktop=screen.getByTestId("desktop-home"),mobile=screen.getByTestId("mobile-home");expect(desktop).toHaveClass("hidden","lg:block");expect(mobile).toHaveClass("lg:hidden");expect(screen.getAllByRole("heading",{name:"Blockchain Savings"})).toHaveLength(2);expect(within(mobile).getByLabelText("Mobile navigation")).toHaveClass("fixed");expect(document.querySelectorAll("#home")).toHaveLength(1);expect(document.querySelectorAll("#features")).toHaveLength(1)});
it("keeps rates numeric and removes annual-rate content",()=>{renderHome();expect(screen.queryByText(/Annual Rate|APR|年化收益/)).not.toBeInTheDocument();for(const layout of[screen.getByTestId("desktop-home"),screen.getByTestId("mobile-home")]){const tables=within(layout).getAllByTestId("rate-table");expect(tables).toHaveLength(2);expect(within(tables[0]).getByRole("heading",{name:/Flexible Savings Rates/})).toBeInTheDocument();expect(within(tables[1]).getByRole("heading",{name:/Fixed Savings Rates/})).toBeInTheDocument();expect(within(tables[0]).getAllByRole("columnheader")).toHaveLength(2);expect(within(tables[0]).getByText("2.70%")).toBeInTheDocument()}});
it("renders four banners, ticker endorsements, and all advantages",()=>{renderHome();expect(screen.getAllByTestId("promo-banner-slide")).toHaveLength(4);expect(screen.getByRole("img",{name:/3 million ETH/})).toBeInTheDocument();expect(within(screen.getAllByTestId("market-ticker-track")[0]).getByText(/On-chain transparency/)).toBeInTheDocument();for(const layout of[screen.getByTestId("desktop-home"),screen.getByTestId("mobile-home")]){const panel=within(layout).getByTestId("advantages-panel");expect(within(panel).getAllByRole("button")).toHaveLength(11);fireEvent.click(within(panel).getByRole("button",{name:/01.*Rewards Program/}));expect(within(panel).getByText(/Review the applicable plan/)).toBeInTheDocument()}});
it("places highlighted tickers where users see them before the rate tables",()=>{renderHome();const desktop=screen.getByTestId("desktop-home"),mobile=screen.getByTestId("mobile-home");const desktopTicker=within(desktop).getByTestId("desktop-highlight-ticker");const mobileTicker=within(mobile).getByTestId("mobile-highlight-ticker");expect(desktopTicker).toHaveClass("market-ticker-highlight");expect(mobileTicker).toHaveClass("market-ticker-highlight");expect(desktopTicker.compareDocumentPosition(within(desktop).getByTestId("desktop-rates"))&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(mobileTicker.compareDocumentPosition(within(mobile).getByTestId("feature-grid"))&Node.DOCUMENT_POSITION_FOLLOWING).toBeTruthy();expect(within(desktopTicker).getAllByText(/On-chain transparency/).length).toBeGreaterThan(0);expect(within(mobileTicker).getAllByText(/On-chain transparency/).length).toBeGreaterThan(0)});
it("switches both PC and H5 content from the shared selector",()=>{renderHome();fireEvent.change(screen.getByRole("combobox",{name:"Language"}),{target:{value:"ja"}});expect(screen.getAllByText("フレキシブル貯蓄金利")).toHaveLength(2);expect(screen.getAllByText("選ばれる理由")).toHaveLength(2);expect(screen.getByRole("link",{name:"ホーム"})).toHaveAttribute("href","/")});
it("opens the mobile menu and exposes all six languages",()=>{renderHome();fireEvent.click(screen.getByRole("button",{name:"Open mobile menu"}));const drawer=screen.getByTestId("mobile-drawer");expect(drawer.parentElement).toBe(document.body);for(const label of["EN","简体","繁体","日本語","한국어","ไทย"])expect(within(drawer).getByRole("button",{name:label})).toBeInTheDocument();fireEvent.click(within(drawer).getAllByRole("button",{name:"Close mobile menu"})[1]);expect(screen.queryByTestId("mobile-drawer")).not.toBeInTheDocument()});
});
