import{fireEvent,render,screen,within}from"@testing-library/react";import PoolPage from"@/app/pool/page";import SavingsPoolPage from"@/app/savings-pool/page";import LoanPage from"@/app/loan/page";import DocsPage from"@/app/docs/page";import{LocaleProvider}from"@/i18n/locale-provider";
const view=(node:React.ReactNode)=>render(<LocaleProvider>{node}</LocaleProvider>);
describe("localized destination pages",()=>{
it("renders the pool workflow in English",()=>{view(<PoolPage/>);expect(screen.getByRole("heading",{name:"Savings Dashboard"})).toBeInTheDocument();expect(screen.getAllByRole("tab")).toHaveLength(4);fireEvent.click(screen.getByRole("tab",{name:"Plans"}));expect(screen.getByRole("heading",{name:"Savings Dashboard"})).toBeInTheDocument();fireEvent.click(screen.getByRole("tab",{name:"Account"}));expect(screen.getByText("Connect your wallet to view account information.")).toBeInTheDocument()});
it("keeps savings plan panel icons behind content and localizes the account action",()=>{view(<PoolPage/>);expect(screen.getByTestId("pool-dashboard")).toBeInTheDocument();expect(screen.getAllByTestId("pool-decorative-icon").length).toBeGreaterThan(0);for(const icon of screen.getAllByTestId("pool-decorative-icon")){expect(icon).toHaveClass("pointer-events-none","z-0")}fireEvent.click(screen.getByRole("tab",{name:"Plans"}));expect(screen.getAllByTestId("pool-decorative-icon")).toHaveLength(2);fireEvent.click(screen.getByRole("tab",{name:"Account"}));expect(screen.getByRole("button",{name:"Connect Wallet"})).toBeInTheDocument();expect(screen.queryByRole("button",{name:"Start Savings"})).not.toBeInTheDocument();expect(screen.getByTestId("pool-account-content")).toHaveClass("relative","z-10");expect(screen.getByTestId("pool-decorative-icon")).toHaveClass("pointer-events-none","z-0");fireEvent.click(screen.getByRole("tab",{name:"Transfer"}));expect(screen.getByTestId("pool-transfer-content")).toHaveClass("relative","z-10");expect(screen.getByRole("button",{name:"Data source not connected"})).toBeDisabled();expect(screen.getByTestId("pool-decorative-icon")).toHaveClass("pointer-events-none","z-0")});
it("keeps all savings plan cards bright while making the rewards gift stand out",()=>{view(<PoolPage/>);const gift=screen.getByTestId("pool-overview-gift-card");expect(gift).toHaveClass("pool-gift-card-bright","border-warning/60","bg-warning/10");const overviewIcons=screen.getAllByTestId("pool-decorative-icon");expect(overviewIcons[0]).toHaveClass("opacity-60");expect(overviewIcons.slice(1).every((icon)=>icon.className.includes("opacity-40"))).toBe(true);fireEvent.click(screen.getByRole("tab",{name:"Plans"}));for(const icon of screen.getAllByTestId("pool-decorative-icon"))expect(icon).toHaveClass("opacity-40");fireEvent.click(screen.getByRole("tab",{name:"Account"}));expect(screen.getByTestId("pool-decorative-icon")).toHaveClass("opacity-40");fireEvent.click(screen.getByRole("tab",{name:"Transfer"}));expect(screen.getByTestId("pool-decorative-icon")).toHaveClass("opacity-40")});
it("renders smart contract matching and yield statistics without showing flexible savings tables",()=>{view(<SavingsPoolPage/>);expect(screen.getAllByRole("tab")).toHaveLength(5);expect(screen.queryByRole("combobox",{name:"Language"})).not.toBeInTheDocument();fireEvent.click(screen.getByRole("tab",{name:"Plan"}));const plan=screen.getByTestId("contract-plan-panel");expect(within(plan).getByRole("spinbutton",{name:"Wallet asset amount"})).toBeInTheDocument();expect(within(plan).getByRole("spinbutton",{name:"Custom lock days"})).toBeInTheDocument();expect(within(plan).queryByRole("combobox",{name:/term|days/i})).not.toBeInTheDocument();expect(plan).not.toHaveTextContent("Flexible Savings");expect(plan).not.toHaveTextContent("distributed every 4 hours");expect(plan).not.toHaveTextContent("50000 * 1.1% / ETH price / 6");expect(plan).toHaveTextContent("Auto matched tier");fireEvent.change(within(plan).getByRole("spinbutton",{name:"Wallet asset amount"}),{target:{value:"50000"}});expect(plan).toHaveTextContent("50,000 - 99,999");expect(plan).not.toHaveTextContent("1.10%");expect(plan).toHaveTextContent("2.20%");const contractButtons=within(plan).getAllByRole("button",{name:"Smart Contract"});expect(contractButtons).toHaveLength(1);fireEvent.click(contractButtons[0]);expect(screen.getByRole("dialog",{name:"Smart Contract Order"})).toHaveTextContent("Custom lock days");fireEvent.click(screen.getByRole("button",{name:"Cancel"}));fireEvent.click(screen.getByRole("tab",{name:"Yield Stats"}));const stats=screen.getByTestId("yield-stats-panel");for(const label of["Total yield cap","Paid ETH","Paid USDC value","Remaining rewards","Current participants"])expect(stats).toHaveTextContent(label)});
it("renders honest unavailable loan states",()=>{view(<LoanPage/>);expect(screen.getByRole("heading",{name:"Loan Service"})).toBeInTheDocument();expect(screen.getByRole("button",{name:"Download Form"})).toBeDisabled();expect(screen.getByText("Available after backend integration")).toBeInTheDocument()});
it("renders verified-document placeholders",()=>{view(<DocsPage/>);expect(screen.getByRole("heading",{name:"Document Center"})).toBeInTheDocument();expect(screen.getByText("Ethereum White Paper")).toBeInTheDocument();expect(screen.getAllByRole("button",{name:"Pending verification"})).toHaveLength(2)});
});
